# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6977b887dccfd4c275437aab75b97557c105962bf3cb78765de87b63b6bd667008dd93e2aa51c10b204f1d2954d2119e9d86bbccea85ec86345d67de533dcb6b

test:
  secret_key_base: 0b7fecd63a36ab0a5c8bde506ce0dfa5a4f535b3ca494e3b5b3a18cf6e96b7b983081dfcd711fdf1d7dbaf9f684312866f89cb5703eaa9cb4f4bc43de058eb6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
